config/routes.rb
D4c::Application.routes.draw do

  root 'home#index'

  resources :users, :only => [:show, :update, :index] do
    collection do
      get :login
    end
  end
  resources :projects, :only => [:show, :index, :create] do
    resources :tips, :only => [:index]
    member do
      get :qrcode
    end
  end
  resources :tips, :only => [:index]
  resources :withdrawals, :only => [:index]

  devise_for :users,
    :controllers => {
      :omniauth_callbacks => "users/omniauth_callbacks"
    }

  

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :deposits # todo: only confirmed deposits that have amount > paid_out
  has_many :tips

  validates :full_name, uniqueness: true, presence: true
  validates :github_id, uniqueness: true, presence: true

  def update_github_info repo
    self.github_id = repo.id
    self.name = repo.name
    self.full_name = repo.full_name
    self.source_full_name = repo.source.full_name rescue ''
    self.description = repo.description
    self.watchers_count = repo.watchers_count
    self.language = repo.language
    self.save!
  end

  def github_url
    "https://github.com/#{full_name}"
  end

  def source_github_url
    "https://github.com/#{source_full_name}"
  end

  def new_commits
    begin
      commits = Timeout::timeout(90) do
        client = Octokit::Client.new \
          :client_id     => CONFIG['github']['key'],
          :client_secret => CONFIG['github']['secret'],
          :per_page      => 100
        client.commits(full_name).
          # Filter merge request
          select{|c| !(c.commit.message =~ /^(Merge\s|auto\smerge)/)}.
          # Filter fake emails
          select{|c| c.commit.author.email =~ Devise::email_regexp }.
          # Filter commited after d4c project creation
          select{|c| c.commit.committer.date > self.deposits.first.created_at }.
          to_a
      end
    rescue Octokit::BadGateway, Octokit::NotFound, Octokit::InternalServerError,
           Errno::ETIMEDOUT, Net::ReadTimeout, Faraday::Error::ConnectionFailed => e
      Rails.logger.info "Project ##{id}: #{e.class} happened"
    rescue StandardError => e
      Airbrake.notify(e)
    end
    sleep(1)
    commits || []
  end

  def tip_commits
    new_commits.each do |commit|
      Project.transaction do
        tip_for commit
        update_attribute :last_commit, commit.sha
      end
    end
  end

  def tip_for commit
    email = commit.commit.author.email
    user = User.find_by email: email

    if (next_tip_amount > 0) &&
        Tip.find_by_commit(commit.sha).nil?

      # create user
      unless user
        generated_password = Devise.friendly_token.first(8)
          user = User.create({
          email: email,
          password: generated_password,
          name: commit.commit.author.name,
          nickname: (commit.author.login rescue nil)
        })
      end

      if commit.author && commit.author.login
        user.update nickname: commit.author.login
      end

      # create tip
      tip = Tip.create({
        project: self,
        user: user,
        amount: next_tip_amount,
        commit: commit.sha
      })

      # notify user
      if tip && user.bitcoin_address.blank? && !user.unsubscribed
        if !user.notified_at || (user.notified_at < (Time.now - 30.days))
          UserMailer.new_tip(user, tip).deliver
          user.touch :notified_at
        end
      end

      Rails.logger.info "    Tip created #{tip.inspect}"
    end

  end

  def available_amount
    self.deposits.where("confirmations > 0").map(&:available_amount).sum - tips_paid_amount
  end

  def unconfirmed_amount
    self.deposits.where(:confirmations => 0).map(&:available_amount).sum
  end

  def tips_paid_amount
    self.tips.non_refunded.sum(:amount)
  end

  def tips_paid_unclaimed_amount
    self.tips.non_refunded.unclaimed.sum(:amount)
  end

  def next_tip_amount
    (CONFIG["tip"]*available_amount).ceil
  end

  def self.update_cache
    find_each do |project|
      project.update available_amount_cache: project.available_amount
    end
  end

  def github_info
    client = Octokit::Client.new \
      :client_id     => CONFIG['github']['key'],
      :client_secret => CONFIG['github']['secret']
    if github_id.present?
      client.get("/repositories/#{github_id}")
    else
      client.repo(full_name)
    end
  end

  def update_info
    begin
      update_github_info(github_info)
    rescue Octokit::BadGateway, Octokit::NotFound, Octokit::InternalServerError,
           Errno::ETIMEDOUT, Net::ReadTimeout, Faraday::Error::ConnectionFailed => e
      Rails.logger.info "Project ##{id}: #{e.class} happened"
    rescue StandardError => e
      Airbrake.notify(e)
    end
  end

  def tips_to_pay
    tips.unpaid.with_address
  end

  def amount_to_pay
    tips_to_pay.sum(:amount)
  end
end

app/controllers/projects_controller.rb
require 'net/http'

class ProjectsController < ApplicationController
  def index
    @projects = Project.order(available_amount_cache: :desc, watchers_count: :desc, full_name: :asc).page(params[:page]).per(30)
  end

  def show
    @project = Project.find params[:id]
    if @project and @project.bitcoin_address.nil? and (github_id = @project.github_id).present?
      label = "#{github_id}@dog4commit"
      address = DogecoinDaemon.instance.get_new_address(label)
      @project.update_attributes(bitcoin_address: address, address_label: label)
    end
  end

  def qrcode
    @project = Project.find params[:id]
    respond_to do |format|
      format.svg  { render :qrcode => @project.bitcoin_address, level: :l, unit: 4 }
    end
  end

  def create
    project_name = params[:full_name].
      gsub(/https?\:\/\/github.com\//, '').
      gsub(/\#.+$/, '').
      gsub(' ', '')
    client = Octokit::Client.new \
      :client_id     => CONFIG['github']['key'],
      :client_secret => CONFIG['github']['secret']
    begin
      repo = client.repo project_name
      @project = Project.find_or_create_by full_name: repo.full_name
      @project.update_github_info repo
      redirect_to @project
    rescue Octokit::NotFound
      redirect_to projects_path, alert: "Project not found"
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def shield_btc_amount amount
    btc_amount = to_btc amount
    "%.#{6 - btc_amount.to_i.to_s.length}f DGC" % btc_amount
  end

  def shield_color project
    last_tip = project.tips.order(:created_at).last
    if last_tip.nil? || (Time.now - last_tip.created_at > 30.days)
      'red'
    elsif (Time.now - last_tip.created_at > 7.days)
      'yellow'
    elsif (Time.now - last_tip.created_at > 1.day)
      'yellowgreen'
    else
      'green'
    end
  end
end

app/views/projects/index.html.haml
%h1 Supported Projects
%p
  = form_tag projects_path, html: {role: 'form', class: 'form-inline"'}, method: :post do |f|
    .form-group
      .row
        .col-lg-10
          = text_field_tag :full_name, '', class: 'form-control', placeholder: 'Enter GitHub project URL to find or add a project e.g. rails/rails'
        .col-lg-2
          %button(type="submit" class="btn form-control btn-default") Find or add project
%p
  %table.table
    %thead
      %tr
        %th Repository
        %th Description
        %th Watchers
        %th Balance
        %th
    %tbody
      - @projects.each do |project|
        %tr
          %td
            %strong= link_to project.full_name, project
            - if !project.source_full_name.blank?
              %br
              %nobr
                %small
                  forked from
                  = link_to project.source_full_name, project.source_github_url, target: '_blank'
          %td= project.description
          %td= project.watchers_count
          %td= btc_human project.available_amount_cache
          %td= link_to 'Support', project, class: 'btn btn-success'
  = paginate @projects

app/views/projects/show.html.haml
- content_for :title do
  Contribute to
  = @project.name
- content_for :description do
  = @project.description
  
%h1
  = @project.full_name
  %small= link_to glyph(:github), @project.github_url, target: '_blank'

.row
  .col-md-4
    .panel.panel-default
      .panel-heading
        %h4.panel-title
          Project Sponsors
      .panel-body.text-center
        %p To give to this project, send dogecoins to this address:
        %p
          = @project.bitcoin_address
        %p
          = image_tag qrcode_project_path(@project, format: :svg), alt: @project.bitcoin_address, class: "project qrcode"
        %p #{100-(CONFIG["our_fee"]*100).round}% of deposited funds will be used to tip for new commits. 
  .col-md-8
    - unless @project.description.blank?
      .well.well-sm= @project.description
    %h4 Balance
    = btc_human @project.available_amount
    (each new commit receives #{(CONFIG["tip"]*100).round}% of available balance)
    - if (unconfirmed_amount = @project.unconfirmed_amount) > 0
      (#{btc_human unconfirmed_amount} unconfirmed)

    %h4 Tips Paid
    = btc_human @project.tips_paid_amount
    - if (tips_paid_unclaimed_amount = @project.tips_paid_unclaimed_amount) > 0
      (#{btc_human tips_paid_unclaimed_amount} of this is unclaimed, and will be refunded to the project after being unclaimed for 1 month.)

    - if @project.tips.count > 0
      %h4
        Last Tips
        - if @project.tips.count > 5
          = link_to 'see all', project_tips_path(@project)
      %ul
        - @project.tips.includes(:user).order(created_at: :desc).first(5).each do |tip|
          %li
            = l tip.created_at, format: :short
            - if tip.user.nickname.blank?
              = tip.user.full_name
            - else
              = link_to tip.user.full_name, "https://github.com/#{tip.user.nickname}", target: '_blank'
            received
            = btc_human tip.amount
            for commit
            = link_to tip.commit[0..6], "https://github.com/#{@project.full_name}/commit/#{tip.commit}", target: :blank

    - if @project.next_tip_amount > 0
      %h4 Next Tip
      = btc_human @project.next_tip_amount

    %h4 Contribute and Earn
    Donate dogecoins to this project or
    = link_to 'make commits', @project.github_url, target: '_blank'
    and get tips for it. If your commit is accepted by project maintainer and there are dogecoins on its balance, you will get a tip!

    - if current_user
      - if current_user.bitcoin_address.blank?
        Just 
        = link_to 'tell us', current_user
        your dogecoin address.      
    - else
      Just check your email or 
      %a{href: user_omniauth_authorize_path(:github)} Sign In.

    %h4 Promote #{@project.full_name}
    %p
      / AddThis Button BEGIN
      .addthis_toolbox.addthis_default_style.addthis_32x32_style(addthis:data_track_clickback="false" addthis:data_track_addressbar="false")
        %a.addthis_button_preferred_1
        %a.addthis_button_preferred_2
        %a.addthis_button_preferred_3
        %a.addthis_button_preferred_4
        %a.addthis_button_compact
        %a.addthis_counter.addthis_bubble_style
      / AddThis Button END

    %h4 Embed in README.md
    %p= link_to image_tag(project_url(@project, format: :svg), alt: 'Doge4Commit'), project_url(@project)
    %p
      %input.form-control{type: 'text', value: "[![tip for next commit](#{project_url(@project, format: :svg)})](#{project_url(@project)})"}

app/views/projects/show.svg.erb
<svg version="1.1"
     xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     width="<%= width = 140 %>px"
     height="18px">
  <defs>
    <linearGradient id="gray" gradientUnits="userSpaceOnUse" x1="0" y1="0" x2="0" y2="18">
      <stop offset="0"    style="stop-color:#AAAAAA" />
      <stop offset="0.1"  style="stop-color:#5A5A5A" />
      <stop offset="0.96" style="stop-color:#3F3F3F" />
      <stop offset="1"    style="stop-color:#2E2E2E" />
    </linearGradient>
    <linearGradient id="lightgray" gradientUnits="userSpaceOnUse" x1="0" y1="0" x2="0" y2="18">
      <stop offset="0"    style="stop-color:#D6D6D6" />
      <stop offset="0.1"  style="stop-color:#9F9F9F" />
      <stop offset="0.96" style="stop-color:#707070" />
      <stop offset="1"    style="stop-color:#515151" />
    </linearGradient>
    <linearGradient id="darkgray" gradientUnits="userSpaceOnUse" x1="0" y1="0" x2="0" y2="18">
      <stop offset="0.0"  style="stop-color:#909090" />
      <stop offset="0.1"  style="stop-color:#313131" />
      <stop offset="0.96" style="stop-color:#232323" />
      <stop offset="1"    style="stop-color:#191919" />
    </linearGradient>
    <linearGradient id="green" gradientUnits="userSpaceOnUse" x1="0" y1="0" x2="0" y2="18">
      <stop offset="0"    style="stop-color:#9DED7D"/>
      <stop offset="0.1"  style="stop-color:#4AD115"/>
      <stop offset="0.96" style="stop-color:#31B70E"/>
      <stop offset="1"    style="stop-color:#23630A"/>
    </linearGradient>
    <linearGradient id="yellowgreen" gradientUnits="userSpaceOnUse" x1="0" y1="0" x2="0" y2="18">
      <stop offset="0"    style="stop-color:#D1F171"/>
      <stop offset="0.1"  style="stop-color:#97CA00"/>
      <stop offset="0.96" style="stop-color:#6B8F00"/>
      <stop offset="1"    style="stop-color:#4D6700"/>
    </linearGradient>
    <linearGradient id="yellow" gradientUnits="userSpaceOnUse" x1="0" y1="0" x2="0" y2="18">
      <stop offset="0"    style="stop-color:#FFE37F"/>
      <stop offset="0.1"  style="stop-color:#E0B417"/>
      <stop offset="0.96" style="stop-color:#9E7F10"/>
      <stop offset="1"    style="stop-color:#725C0C"/>
    </linearGradient>
    <linearGradient id="red" gradientUnits="userSpaceOnUse" x1="0" y1="0" x2="0" y2="18">
      <stop offset="0"    style="stop-color:#FFAC9C"/>
      <stop offset="0.1"  style="stop-color:#E05D44"/>
      <stop offset="0.96" style="stop-color:#9E4230"/>
      <stop offset="1"    style="stop-color:#722F22"/>
    </linearGradient>
    <filter id="dropshadow" height="100%">
      <feGaussianBlur in="SourceAlpha" stdDeviation="0"/>
      <feOffset dx="0" dy="1" result="offsetblur"/>
      <feComponentTransfer xmlns="http://www.w3.org/2000/svg">
        <feFuncA type="linear" slope="0.3"/>
      </feComponentTransfer>
      <feMerge> 
        <feMergeNode/>
        <feMergeNode in="SourceGraphic"/>
      </feMerge>
    </filter>
    <style type="text/css">
      <![CDATA[
        @font-face {
          font-family: 'Open Sans';
          font-style: normal;
          font-weight: 400;
          src: local('Open Sans'), local('OpenSans'), url(http://themes.googleusercontent.com/static/fonts/opensans/v6/cJZKeOuBrn4kERxqtaUH3bO3LdcAZYWl9Si6vvxL-qU.woff) format('woff');
        }
      ]]>
    </style>
  </defs>
  
  <g id="vendor">
    <path d="M0,9 v-6 q0,-3,3,-3 v18 q-3,0,-3,-3 Z" fill="url(#gray)" />
    <rect x="3" y="0" width="<%= width1 = 67 %>" height="18" fill="url(#gray)" />
    <text x="6" y="12" font-family="Open Sans" font-size="10" fill="#FFFFFF" style="filter:url(#dropshadow)">
          dog4commit
    </text>
  </g>

  <g id="status">
    <rect x="<%= width1 + 3 %>" y="0" width="<%= width - width1 - 6 %>" height="18" fill="url(#<%= shield_color @project %>)" />
    <path fill="url(#<%= shield_color @project %>)" d="M<%= width %>,9 v-6 q0,-3,-3,-3 v18 q3,0,3,-3 Z" />
    <text x="<%= width1 + 7 %>" y="12" font-family="Open Sans" font-size="10" fill="#FFFFFF" style="filter:url(#dropshadow)">
          <%= shield_btc_amount @project.next_tip_amount %>
    </text>
  </g>
</svg>